# Generated by Django 4.2.7 on 2023-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=30, verbose_name='role'),
        ),
    ]
