# Generated by Django 4.2.7 on 2023-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_course_user_remove_lesson_user_course_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(blank=True, null=True, verbose_name='видео'),
        ),
    ]
